# Generated by Django 4.2.3 on 2023-08-08 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_materials_created_at_materials_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='дата создания'),
        ),
    ]
