# Generated by Django 4.2.3 on 2023-08-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_alter_materials_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='materials',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
