# Generated by Django 4.2.3 on 2023-09-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='email',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='почта'),
        ),
    ]
