# Generated by Django 4.2.3 on 2023-09-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='наименование'),
        ),
        migrations.AlterField(
            model_name='version',
            name='version_number',
            field=models.IntegerField(default=0.0, verbose_name='номер версии'),
        ),
    ]
